### ISSUE TITLE
JWT Handling of edge case VCs

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VP#1]
### Original Reporter: dwc8

It is expected that the majority of VCs will hold attributes about a single subject and consequently have a single subject ID. When this is secured as a JWT, the subject ID is turned into the sub claim. However, there are some exceptions.

1. Bearer VCs have no subject ID
2. Some VCs may have two or more subject IDs e.g. a marriage certificate.

How are bearer credentials and multi-subject credentials to be converted into a JWT for inclusion in the VP? What value should the sub claim contain?

‌

**Comment by awoie** [comment]
The specification currently says:

> The Wallet MUST link every Verifiable Presentation returned to the Verifier in the VP Token to the client_id and the nonce values of the respective Authentication Request.

> The Verifier MUST validate every individual Verifiable Presentation in an Authorization Response and ensure that it is linked to the values of the client_id and the nonce parameter it had used for the respective Authorization Request.

I'm not sure if your use case is supported by the OID4VP specification. Unless the bearer VC itself contains the nonce/client_id.

**Comment by awoie** [comment]
potential duplicate of #6

**Comment by Sakurann** [comment]
> Bearer VCs have no subject ID

-> duplicate of #6

> Some VCs may have two or more subject IDs e.g. a marriage certificate.

it should be clear to the wallet which key(s) to use to proof possession of that credential (potentially multiple signatures for proof of possession). this is at the credential format level and not oid4vp level and this use-case is already supported by oid4vp.
