### ISSUE TITLE
Presentation Exchange doesn't have the `mdoc-mso` entry in its Registry?

### ISSUE THREAD

**Issue by samuelgoto** [openid/OpenID4VP#107]
I was reading the [mdoc section](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-iso-mobile-driving-license-) of this spec and ran into this code example of Presentation Exchange:

```json
"format":{
  "mso_mdoc":{
    "alg":[
      "EdDSA",
      "ES256"
    ]
  },
},
```

But following the Presentation Exchange spec leads me to [this](https://identity.foundation/claim-format-registry/#registry) Registry, which doesn't seem to think `mso_mdoc` is a valid entry.

Is this just a spec bug?

**Comment by Sakurann** [comment]
We haven't really been using DIF.PE registry, but rather defined credential format identifiers in OpenID4VP spec directly. It is a no-brainer to register these identifiers (including sd-jwt vc, etc) with PE if you think it is important, it just has not been prioritized.

**Comment by samuelgoto** [comment]
> rather defined credential format identifiers in OpenID4VP spec directly

Can you point me where that's define in the OpenID4VP spec? Is there maybe a registry of formats that I may have missed?

**Comment by Sakurann** [comment]
each section in Appendix A has a sentence `The Credential format identifiers are ...`. Guess it could be clearer.

**Comment by decentralgabe** [comment]
Addressed in https://github.com/decentralized-identity/claim-format-registry/pull/11 please take a look for correctness

**Comment by samuelgoto** [comment]
LGTM. Resolving.
