### ISSUE TITLE
Response Endpoint may not be suffciently described

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VP#111]
as discussed on DCP call

**Comment by Sakurann** [comment]
to add color, OID4VP currently uses a term `Response Endpoint` to point to a Verifier's endpoint that receives the response from the Wallet with requested VC(s). but that might not be stated clearly enough in the text

**Comment by Sakurann** [comment]
Agreed to replace `Response Endpoint` with `Response URI`. (to be consistent with `response_uri` parameter name).
+ Update definition to `response_uri` to say it is a URL.
