### ISSUE TITLE
Improvement on `x509_san_dns` & `x509_san_uri`

### ISSUE THREAD

**Issue by babisRoutis** [openid/OpenID4VP#116]
Currently (draft 20) contains the following:

> x509_san_dns: When the Client Identifier Scheme is x509_san_dns, the Client Identifier MUST be a DNS name and match a dNSName Subject Alternative Name (SAN) [[RFC5280](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#RFC5280)] entry in the leaf certificate passed with the request. The request MUST be signed with the private key corresponding to the public key in the leaf X.509 certificate of the certificate chain added to the request in the x5c JOSE header [[RFC7515](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#RFC7515)] of the signed request object. The Wallet MUST validate the signature and the trust chain of the X.509 certificate. All Verifier metadata other than the public key MUST be obtained from the client_metadata parameter. If the Wallet can establish trust in the Client Identifier authenticated through the certificate, e.g. because the Client Identifier is contained in a list of trusted Client Identifiers, it may allow the client to freely choose the redirect_uri value. If not, the FQDN of the redirect_uri value MUST match the Client Identifier.

I believe that the last phrase ( _FQDN of the redirect_uri value MUST match the Client Identifier_ ) is not totally correct since it describes a description only for `redirect_uri`.
Yet, in case we have `x509_san_dns` and `direct_post.jwt` we cannot use `redirect_uri`. Rather we must use `response_uri`.
Thus, the above constraint is applicable only when response mode is NOT `direct_post` or `direct_post.jwt`

Perhaps the constraint should be updated to refer to the FQDN of either the `redirect_uri` or the `response_uri` depending on the response mode.

The same is true also for `x509_san_uri` description where there is the constraint _If not, the redirect_uri value MUST match the Client Identifier._

**Comment by jogu** [comment]
This behaviour is consistent across all client authentication types so it currently documented in https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#section-6.2 :

> response_uri:
> REQUIRED when the Response Mode direct_post is used. (...). The response_uri value MUST be a value that the client would be permitted to use as redirect_uri when following the rules defined in [Section 5.7](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#client_metadata_management).

**Comment by awoie** [comment]
We had this issue already and added the language @jogu quoted for this reason.

**Comment by babisRoutis** [comment]
@jogu @awoie 

Thanks for the feedback. 

I had impression that description of san_dns & san_uri was putting a constraint on client_id. From this point of view, I thought that the constraint was not complete.

In 6.2 constraints focus rather on redirect_uri & response_uri and indeed the rule exists.

Closing the issue
