### ISSUE TITLE
Inconsistent examples for jwt_vp

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#122]
There are various things that look like inconsistencies in the jwt_vp examples, e.g.:

<img width="507" alt="Screenshot 2024-03-05 at 17 57 48" src="https://github.com/openid/OpenID4VP/assets/316456/bf74270c-5899-40c5-bc6e-c784e46c4bb6">

The VP spec only defines `jwt_vp_json`, so `jwt_vp` there should probably be changed to `jwt_vp_json`.

We have some presentation examples that use `"format": "jwt_vp"` and some with "format": "jwt_vp_json". I am not sure which should be used but I presume we should be consistent. `jwt_vp_json` does not exist in the PE registry: https://identity.foundation/claim-format-registry/#registry

**Comment by jogu** [comment]
@Sakurann 

> for the vcdm v1.1, for the VCs there is a distinction between jwt_vc_json and jwt_vc_json-ld (which is defined in VCI, but not VP), but for VP I think that distinction matters less, so jwt_vp might be ok.

To clarify, are you suggesting we change the type that VP defines from `jwt_vc_json` to `jwt_vc`  here:

https://github.com/openid/OpenID4VP/blob/main/openid-4-verifiable-presentations-1_0.md?plain=1#L1375


(I was presuming we wouldn't want to make a breaking change like that and would just fix the examples...)

**Comment by Sakurann** [comment]
I was suggeting to use jwt_vc_json and jwt_vp, but you are right, spec text itself defines jwt_vp_json, so I did a PR #145 to stick to jwt_vp_everywhere
