### ISSUE TITLE
Appendix 'A' is labelled "Examples" but contains normative text

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#142]
Appendix 'A' is labelled as "Examples" but it contains normative text, particularly once the SD-JWT VC PR is merged.

We should probably tweak the title.

**Comment by Sakurann** [comment]
i think situation right now is as such that both VCI and VP define credential format profiles, but OID4VCI does it normatively (in Appendix A btw) while VP is not clear if it does so normatively or not. and direction has been to make this annex A normative.

**Comment by Sakurann** [comment]
issue #55 might be duplicative.

**Comment by Sakurann** [comment]
agreed appendix A in VP should be normative. removing a term "examples" sounds the easiest thing to do.
