### ISSUE TITLE
Add SD-JWT example to VP Token Examples

### ISSUE THREAD

**Issue by danielfett** [openid/OpenID4VP#149]
Current examples in Section 6.1 only show W3C VCs. I think the spec would benefit from an SD-JWT (VC) example.

**Comment by Sakurann** [comment]
I think we need a policy which credential format to use in the examples in the main spec text. previously there has been a comment that it should be mdocs to prove that oid4vc is not only about JSON credential formats. either we show the all examples 1) consistently in one format, or 2) consistently in multiple formats or 3) ok with each example being in a different format..

**Comment by Sakurann** [comment]
agreed to substitute jwt_vp_json example in section 6.1 to sd-jwt vc example to have different formats

**Comment by jruizaranguren** [comment]
@bc-pi, just tell me if I can be of any help.
