### ISSUE TITLE
query language requirements discussion: multiple credentials in one request?

### ISSUE THREAD

**Issue by Sakurann** [openid/OpenID4VP#162]
Should verifier be able to request the Wallet to return multiple credentials in one request? (multiple comments, need an explicit agreement that this feature itself is a requirement, though it might not end up being mandatory to implement for some)

**Comment by jogu** [comment]
> Will the browser API support multi-credentials ever? Latest statement from platform vendors was that this won't be the case

I don't recall a statement like that, though it very much depends on the definition of 'support'. I thought there was general agreement in WICG that the browsers would not block a wallet from returning multiple credentials for a single request, albeit currently the browser would show this as a single credential in the browser-owned credential/wallet selector dialogue.

**Comment by awoie** [comment]
> > Will the browser API support multi-credentials ever? Latest statement from platform vendors was that this won't be the case
> 
> I don't recall a statement like that, though it very much depends on the definition of 'support'. I thought there was general agreement in WICG that the browsers would not block a wallet from returning multiple credentials for a single request, albeit currently the browser would show this as a single credential in the browser-owned credential/wallet selector dialogue.

I could be wrong which is why I caveated. Wouldn't platform vendors need to do something on the matcher screen to support multiple credentials? I believe at least on Android?

**Comment by jogu** [comment]
> Wouldn't platform vendors need to do something on the matcher screen to support multiple credentials? I believe at least on Android?

You end up with the somewhat awkward position where the platform thinks it's showing a single credential to the user for them to select, but what the wallet provided to be shown to the user is actually a composite credential made up of two credentials. (So, e.g., "Driving license and university degree" might be shown to the user as a single entity in the credential picker.)

It's probably not an ideal user experience and probably once we have some implementation examples we can have a conversation in WICG about improving it.

**Comment by David-Chadwick** [comment]
We seem to be mixing up this requirement with the browser API requirements. If we ignore the browser API for a minute, then I think requesting multiple credentials is a requirement of the VP protocol, albeit an optional one. The less wallets the user has, the more valuable this feature becomes, with maximum utility if the user only has one wallet holding all their credentials. If we consider the browser API, this is primarily for choosing between wallets. It might be in the early days of VCs, users will have several wallets, but I would expect them to migrate towards a single wallet as the market consolidates, at which time the browser API becomes less useful (although it still has some useful features such as verifying origins and eliminating the need for custom URLs). So we might expect the browser API to improve in the longer term to support multiple credentials and pulling different credentials from different wallets.

**Comment by selfissued** [comment]
As I wrote in my comments at https://github.com/openid/OpenID4VP/issues/157#issuecomment-2081289581 , requesting and receiving multiple credentials should not be mandatory to implement.  I am OK with there being an optional to implement syntax for doing this.

**Comment by bc-pi** [comment]
> We seem to be mixing up this requirement with the browser API requirements. 

Yeah but it's difficult to disentangle the two with the hope/expectation that the OID4VP profile for the W3C Digital Credentials API #155 will gain traction and the possibility that in doing so it largely supplants the "traditional" OID4VP flows. I think, for the longer term viability and relevance of OID4VP, it's important to at least keep the browser API context in mind for the query language discussions.

**Comment by Sakurann** [comment]
discussed in the WG. agreed to keep the requirement to support presentation of multiple credentials. whether it is mandatory to implement remains.
