### ISSUE TITLE
Payment Authorizations - Consider the EMV method

### ISSUE THREAD

**Issue by cyberphone** [openid/OpenID4VP#180]
I hope nobody takes offence but traditional payment authorization systems like EMV (as well as Apple Pay), perform SCA (Strong Customer Authentication) in a very different way than schemes based on OAuth.  The sequence diagram below should give you an idea. Core features of this flow include:
- Simple and _stateless_ operation.
- Support for _multi-phase transactions_ needed for gas-station payments, subscriptions, deposits, etc.
- Support for arbitrary account-based payment networks without any wallet modifications.

In short it works like this: In step **4** a payer authorization object is created and then pushed (by the Merchant) onto the (for the selected payment credential suitable) payment backend for processing.  Eventually the payer authorization object ends up at the Payer Bank (point **T**) where the actual verification takes place.  More details can be found in: https://cyberphone.github.io/doc/saturn/saturn-core-flow.pdf.

The only drawback I'm aware of is that PII-related authorization data (like account and signature key id), must be _encrypted_.  To maintain privacy, the encryption [public] key must be shared by multiple Payers.  Merchants and payment intermediaries only need to know the end-point to the Payer's Bank and the payment method associated with the selected payment credential.

Although I have not tested it, using BLE, the Wallet should work without Internet connectivity, like payment cards always did.

That this flow isn't aligned with OAuth is not only due to historical reasons, but to the fact that the Merchant represents an _additional entity_, not covered by OAuth-based standards.

<img width="1400" alt="Screenshot 2024-05-24 at 15 23 42" src="https://github.com/openid/OpenID4VP/assets/8044211/bbd8e720-fedb-4967-b1c2-b0196a023740">

**Comment by Sakurann** [comment]
I don't think the proposal is to replace all steps 1~11 with OAuth or wallet-based model. If my understanding is correct, the proposal is to use OpenID4VP + transaction data in steps 2~5 in the diagram, when the user is being identified and user authorization is being gathered. (equivalent to [this diagram](https://github.com/digitallabor-berlin/eudiw-sca/blob/main/openbanking-r2s.md#sca-payment-authorization) in digitallabor-berlin document)

**Comment by cyberphone** [comment]
@Sakurann I don't know where this discussion should be held, but the mentioned specification requires more than twice as many protocol steps while offering half of the functionality compared to the almost 30 year old EMV standard (after applying a _very modest_ update).  Maybe a more neutral party like https://www.sprind.org/en/ could take the lead?
@tlodderstedt

**Comment by cyberphone** [comment]
## Payment Wallets - Feature List
For the market, who don't care (or know anything about) OAuth, EMV, Open Banking, SCA, etc., the following picture is supposed to provide a reasonably fair description of the _current_ status.  For completeness, I included the "Gold Standard" as a reference as well.
<img width="1250" alt="wallet-openid-saturn-apple" src="https://github.com/openid/OpenID4VP/assets/8044211/732c473c-781f-4c0d-bb13-754a3c21b4d8">

**Comment by cyberphone** [comment]
This issue is really about the SCA-flow and its implications.  Given the lack of interest in this topic, I think it is reasonable to close it.

**Comment by cyberphone** [comment]
Progress!  https://github.com/digitallabor-berlin/eudiw-sca/blob/ea5db12b59f583f79e3c866896565fa6c93ae2e4/openbanking-r2s.md
now only requires a single authorization step 😁 

However, the spec. still talks about "*Wallet asking the payer to consent to the presentation of a payment credential...*" which is wrong.  Merchants are not relying parties/verifiers.

A huge improvement is that the spec. now acknowledges that **there currently is no suitable interface in banks**:
>Although currently there is no out of-the-box support for payment initiation using a verifiable presentation in existing OpenBanking standards like the Berlin Group yet, they already specify very similar concepts using a so called "signed payment request" within their Protocol Functions and Security Measures document for the OpenFinance framework, section 7.1

This is a horrible solution that I was personally involved in developing mid 2020 😱  I asked the ad-hoc WG to remove my name from the spec. since I had (during the work) come up with a more agile concept which I also have tested in practice:
https://cyberphone.github.io/doc/defensive-publications/openbanking-evolution.pdf
AFAIK, the Berlin Group doesn't build PoCs.

**Comment by cyberphone** [comment]
Since the DigitalLabor specification have over a period of only 6 months, gone through 3 completely different iterations, it seems that things are in flux, and would benefit from being spun off: https://github.com/openid/OpenID4VP/issues/188
