### ISSUE TITLE
QES for payment authorizations

### ISSUE THREAD

**Issue by cyberphone** [openid/OpenID4VP#187]
Although it might sound great to use qualified certificates for signed payment authorizations, existing systems rarely do, because the Issuer is also the RP.

I would save QES for another day.

**Comment by Sakurann** [comment]
not clear what the issue is asking for or how it is related to openid4vp

**Comment by cyberphone** [comment]
Using the proposed EMV SCA flow (https://github.com/openid/OpenID4VP/issues/180), OpenID4VP requests and presentations get another role.
