### ISSUE TITLE
`vct` matching in credential queries

### ISSUE THREAD

**Issue by danielfett** [openid/OpenID4VP#193]
[This comment](https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/pull/160#issuecomment-2117092649) highlighted a problem that we have not addressed explicitly in OpenID4VP yet:
 
The hierarchy idea behind VCTs doesn't translate well into presentation exchange. PE does string matching, but with SD-JWT VC, what we want is that a request for (or offer of) a credential of type X can lead to a response containing type Y if Y inherits from X. PE only does string matching, which is not sufficient here. For the [new query language](https://github.com/openid/OpenID4VP/issues/178), this can be solved easily - it would just be defined that way for the format vc+sd-jwt.

Another way could be to define this as a processing rule within the SD-JWT VC.

**Comment by awoie** [comment]
> Another way could be to define this as a processing rule within the SD-JWT VC.

I think this is also what was done for ISO mdocs. I would be fine with this.

**Comment by Sakurann** [comment]
> Another way could be to define this as a processing rule within the SD-JWT VC.
> 
> > I think this is also what was done for ISO mdocs. I would be fine with this.

+1 to Oliver.

**Comment by c2bo** [comment]
> > Another way could be to define this as a processing rule within the SD-JWT VC.
> > > I think this is also what was done for ISO mdocs. I would be fine with this.
> 
> +1 to Oliver.

Sounds reasonable; +1

**Comment by joelposti** [comment]
Just for information to any reader of this issue. The latest released OID4VP draft 21 (dated 2024-08-09) contains a new section [B.4. IETF SD-JWT VC](https://openid.net/specs/openid-4-verifiable-presentations-1_0-21.html#name-ietf-sd-jwt-vc) that presents in subsection [B.4.3.Presentation Request](https://openid.net/specs/openid-4-verifiable-presentations-1_0-21.html#name-presentation-request-5) an example of a presentation definition that a relying party/verifier uses to select a credential having a specific `vct` claim value:

```json
{
  ...
  "input_descriptors": [
    {
      ...
      "constraints": {
        ...
        "fields": [
          {
            "path": ["$.vct"],
            "filter": {
              "type": "string",
              "const": "https://credentials.example.com/identity_credential"
            }
          },
          ...
        ]
      }
    }
  ]
}
```

Such `vct` claim matching makes the credential request bound to a specific issuer, and via the digest in `vct#integrity` claim bound to a specific version of the issuer's SD-JWT VC Type Metadata document.
