### ISSUE TITLE
PE Schema Validation Problems

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VP#2]
### Original Reporter: @David-Chadwick 

Currently some non-trivial examples of presentation definitions from the DIF PE specification are causing OIDC schema validation to fail. One example is if a VC contains a set of values, and the PD tries to choose one of the set by using “oneOf” or “anyOf”. This issue has been raised in the DIF PE group \(see [https://github.com/decentralized-identity/presentation-exchange/issues/280](https://github.com/decentralized-identity/presentation-exchange/issues/280) and [https://github.com/decentralized-identity/presentation-exchange/issues/303](https://github.com/decentralized-identity/presentation-exchange/issues/303) \)

DIF say they are using the JSON schema defined in [https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02) which allows more complex constructs such “oneOf” and “anyOf”.

The current workaround for OIDC has been to use simpler examples in the OIDC specifications.

This issue is a placeholder to ensure that any problems with schema validation are resolved before the final specification is published

**Comment by Sakurann** [comment]
(Issue in the PE spec has been closed, but i don't think this issue is resolved?)

**Comment by decentralgabe** [comment]
The solution here is to specify a version of JSON Schema to use. The PE spec today references Draft 7 so it may be simplest to enshrine that in the v2.X spec. I will recommend that to the DIF group.

**Comment by decentralgabe** [comment]
I have opened https://github.com/decentralized-identity/presentation-exchange/issues/480

**Comment by decentralgabe** [comment]
https://github.com/decentralized-identity/presentation-exchange/pull/481

**Comment by decentralgabe** [comment]
this should be addressed by specifying Draft 7 here https://github.com/decentralized-identity/presentation-exchange/pull/481

closing this now, please re-open if this solution is insufficient. 

there may be work in the OID4VP spec to specify JSON Schema Draft 7.
