### ISSUE TITLE
Signed payment requests are impractical

### ISSUE THREAD

**Issue by cyberphone** [openid/OpenID4VP#205]
In https://github.com/digitallabor-berlin/eudiw-sca/blob/ea5db12b59f583f79e3c866896565fa6c93ae2e4/openbanking-r2s.md#payment there is a line:

4. Verify the signature of the authorisation request

Although this seem logical it introduces dependencies on wallet-local trust anchors which complicate deployment.  In addition, this scheme (guessing here...) makes the Payer the initiator since it is the Payer's signature that embeds the Payee request including the Payee receive account.

A more scalable and flexible solution is that the request is unsigned as well as free from merchant account information.  To make this secure and trustworthy, the authorization response is put in a new container which is subsequently signed by the Payee.   The correctness of the created object is then off-loaded to the payment backend.  The Payee cannot change anything in the authorization response since it is signed by the Payer.  WYSIWYS.

The core idea here is keeping the wallet as simple as possible.

This is how EMV payment terminals work as well.

**Comment by jogu** [comment]
Hi @cyberphone 

Unsigned requests are permitted by the OpenID4VP specification. What action are you requesting the DCP WG takes?

**Comment by jogu** [comment]
We (the DCP WG) are not really in a position to tell DigitalLabor that they shouldn't use signed requests. (There's a very high chance that EU law requires them to use signed requests anyway, certainly the conclusion at this point on other credential requests to EU wallets is that the law requires them to be signed.)

**Comment by cyberphone** [comment]
> We (the DCP WG) are not really in a position to tell DigitalLabor that they shouldn't use signed requests.

Right, https://github.com/openid/OpenID4VP/issues/188 is the only issue the DCP WG needs to bother with.
Without a defined trust-, privacy-, and security-model we are left with opinions only.

According to some people on LinkedIn, the latest draft even violates PSD2 by letting the Payee run the show.  Apparently this needs some discussions as well.

> (There's a very high chance that EU law requires them to use signed requests anyway, certainly the conclusion at this point on other credential requests to EU wallets is that the law requires them to be signed.)

This makes perfect sense for *identity-related operations* where you want to assure that the requester is authentic. 

However, *payment-standards* such as EMV or W3C's SPC do not build on such assumptions; they delegate the check to the backend.  Security-wise this is (AFAICT...) identical, while scaling becomes unlimited.  That is, if you accidentally authorize a transaction to a fraudulent merchant, this will be caught by the backend and the request will be denied.  There is already a ton of other error conditions that cannot be cleared upfront, with "insufficient funds" likely being the most common 😆

**Comment by jogu** [comment]
As per above we only need to worry about #188 so closing this one.
