### ISSUE TITLE
Authorizations for multi-phase payments

### ISSUE THREAD

**Issue by cyberphone** [openid/OpenID4VP#207]
Since the revised specification uses an EMV-like SCA-flow, it can now (theoretically) support gas station payments and similar.  This is (IMO) necessary for making the system comparable to Apple Pay et. al. 

Related: https://github.com/openid/OpenID4VP/issues/188

**Comment by jogu** [comment]
I don't think this is in scope for this working group as it's not talking about one of our specifications. Any discussion about expanding scope can be kept under #188 I think.
