### ISSUE TITLE
Aims of OID4VP payment support

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#208]
Is there a nice introduction to the goals of EU wallet based payment system somewhere?

I'm really struggling to get my head around the details of the problem it is trying to solve.

In particular what are the advantages of something like https://github.com/digitallabor-berlin/eudiw-sca/blob/ea5db12b59f583f79e3c866896565fa6c93ae2e4/openbanking-r2s.md#payment compared to just letting wallets get standard OAuth2 based tokens that let them initiate payments via OpenBanking APIs? e.g. Is it just that it shifts some liability onto the payee?

**Comment by jogu** [comment]
The WG call on 8th August will have some payments people presenting their use cases which will hopefully cover this.

**Comment by cyberphone** [comment]
@jogu There are tons of issues here, but liability shift is not one of them.
A non-exhausting list:
- Considerably simpler wallet.
- Stateless operation.
- User conversation is between the Payee, leaving out the ASPSP and PISP.  This also makes NFC payments possible without requiring the mobile data connectivity.
- Payment network neutral.  Supporting VISA/MasterCard/EPI may be important.
- Enables the Payee to chose PSP.
- Deals with multi-phase payments in a more natural way than VRP.
- Opens the path to P2P payments.
- Enables intrinsic support for account balance data 

Last but not least, potentially enables a more decentralized authorization concept which also removes the current single point of failure:
![saturnflows li](https://github.com/user-attachments/assets/2d1c4a04-0c87-44e4-9fd0-411664bf1f50)

The primary drawback is that you need new Open Banking APIs.

**Comment by cyberphone** [comment]
An even bigger problem than the wallet and associated flows, is the monolithic nature of current Open Banking architectures, making new or revised APIs daunting, expensive, and time-consuming.   It also makes testing and development using "sandboxes" impossible.  The Berlin Group's "Signed Payment Request", intended to be used with DigitalLabor's wallet is an _empty shell_.  The need for unique and proprietary implementations in every bank, is a guarantee for extended lead-times and limited "enthusiasm".  In addition, the EU banks have already poured over € 1BN into EPI.
@sakimura

**Comment by Sakurann** [comment]
@jogu could we close this issue with the presentation on the payments use-case that seemed to convince the WG of the need for this use-case? https://lists.openid.net/pipermail/openid-specs-digital-credentials-protocols/Week-of-Mon-20240812/000423.html

**Comment by jogu** [comment]
Yes, as the reporter I'm happy for this to be closed so will close it now.

**Comment by jogu** [comment]
> @jogu Since this issue has been closed, I guess the solution recommended by OpenID is to build on OAuth2? Doesn't the fact that DigitalLabor use another solution motivate a broader discussion around the payment use-case?

I don't understand the question, given that DigitalLabor link is building on top of OpenID4VP which is building on top of OAuth2.

**Comment by cyberphone** [comment]
The issue is the one you started with.  I.e. DigitalLabor do not use OAuth2 flow and tokens.  They use Signed Payment Request which has no OpenId or FAPI counterpart.

**Comment by cyberphone** [comment]
The other EUIDW project targeting payments (https://eudiwalletconsortium.org/project/) have not published their solution.

**Comment by jogu** [comment]
Oh right, the access tokens part - right - that was explained in the presentation Kristina linked to I believe: https://lists.openid.net/pipermail/openid-specs-digital-credentials-protocols/Week-of-Mon-20240812/000423.html

**Comment by cyberphone** [comment]
Without a sequence diagram I'm unable to decipher what is proposed.

_"include dynamic information to be signed by the user and then returned to the RP"_
Given the lack of a sequence diagram, it is unclear who the RP is.  Presumably it is the bank but how does this flow relate to Open4VP?  Requester and Verifier are different parties?

_"articulate which key the user is supposed to use for this operation (as the user may have multiple and not all may be known to the RP)"_
Key?  Aren't we talking virtual payment cards?
