### ISSUE TITLE
What is effective client_id in unsigned browser requests?

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#213]
The browser API appendix says:

> The `client_id` and `client_id_scheme` MUST be omitted in unsigned requests defined in (#unsigned_request). The Wallet determines the Client Identifier from the origin as asserted by the Web Platform and/or app platform.

I'm not clear if "determines" here means "client_id is the origin". If it's not we need to say what we do mean as the the verifier needs to know what value it needs to check for in `aud` in the response.

**Comment by jogu** [comment]
In the unsigned request section it says:

> In this case, the Wallet will use the Verifier's origin as asserted by the Browser as the Verifer's Client Identifier

So I think we just need to update the language in the "determines" clause to make it more direct.

**Comment by bc-pi** [comment]
https://github.com/openid/OpenID4VP/pull/263#discussion_r1775606935 if accepted and then the PR merged, I think, might address this issue

**Comment by Sakurann** [comment]
addressed in PR #263
