### ISSUE TITLE
[JARM] Additional clarifications about signed JWT, Nested JWT and encrypted JWT

### ISSUE THREAD

**Issue by peppelinux** [openid/OpenID4VP#216]
Regarding the section [Signed and/or Encrypted Responses](https://github.com/openid/OpenID4VP/blob/main/openid-4-verifiable-presentations-1_0.md#signed-andor-encrypted-responses-jarm).

To provide concrete guidance for implementations, I suggest the following change:

`To sign, or sign and encrypt the Authorization Response, implementations MAY use JWT Secured Authorization Response Mode for OAuth 2.0 (JARM) [@!JARM].`

to 

`To sign, encrypt, or both sign and encrypt the Authorization Response using a Nested JWT [RFC7519], implementations must utilize the JWT Secured Authorization Response Mode for OAuth 2.0. (JARM) [@!JARM].`

In addition to this, I would open a conversation about how a wallet is supposed to provide its public keys to the verifier for the signature validation, when the signed JWT or the Nested JWT is used. I suppose using wallet_metadata and or wallet instance attestation. we need to better clarify this if we agree

**Comment by Sakurann** [comment]
please do a PR for your suggested updated text. I thnk it makes sense.

**Comment by Sakurann** [comment]
> In addition to this, I would open a conversation about how a wallet is supposed to provide its public keys to the verifier for the signature validation, when the signed JWT or the Nested JWT is used. I suppose using wallet_metadata and or wallet instance attestation. we need to better clarify this if we agree

I think we have a separate issue on this?
