### ISSUE TITLE
Payment credential specification

### ISSUE THREAD

**Issue by cyberphone** [openid/OpenID4VP#222]
I can't find it :(

**Comment by Sakurann** [comment]
I am sorry, it is hard to help without any details. if you are looking for transaction_data related issues, they are labelled as such. and there is draft PR #197

**Comment by cyberphone** [comment]
Presumably DigitalLabor have already implemented support for payment credentials (virtual payment cards).  I'm just curious to see what they have done.

Here is something I did a while ago:https://fido-web-pay.github.io/specification/#credentialdatabase
