### ISSUE TITLE
Advice on the presentation exchange protocol version

### ISSUE THREAD

**Issue by patextreme** [openid/OpenID4VP#231]
In the oid4vp spec, every reference to the presentation exchange protocol seems to point to the [presentation exchange version 2.0](https://identity.foundation/presentation-exchange/spec/v2.0.0/). For implementers, I am not sure what is the semantic of this version. Does this means that any implementation should pin the presentation exchange protocol to version 2.0.0. I'm asking this because there is a newer version 2.1.1 now and whether this should be bumped in the oid4vp spec or pinned to specific version.

If it should be bumped in the oid4vp spec, what would be the mechanism to discover what version the implementation is using? :thinking:

**Comment by Sakurann** [comment]
I have not been following PE recently, did PE 2.1.1 introduce breaking changes from 2.0.0?

**Comment by patlo-iog** [comment]
The schema of `presentation_definition` and `presentation_submission` remain unchanged, I skimmed through the diffs between version and it seems the notable one is `JsonPath`  reference. Hard for me to say anything about compatibility ATM. Do you have any suggestion? I could open an issue on PE to move this forward.

**Comment by patextreme** [comment]
The schema of presentation_definition and presentation_submission remain unchanged, I skimmed through the diffs between version and it seems the notable one is JsonPath reference. Hard for me to say anything about compatibility ATM. Do you have any suggestion? I could open an issue on PE to move this forward.

**Comment by Sakurann** [comment]
if there are no normative changes between PE 2.0.0 and the latest version, i agree openid4vp spec should reference the latest version. would be great if you could confirm this (i am also curious if the changes btw 2.0.0 and the latest version are editorial/adding features?)
