### ISSUE TITLE
Browser API example unsigned request appears not to be conformant with the spec text

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#244]
At https://openid.net/specs/openid-4-verifiable-presentations-1_0-21.html#appendix-A.2 the example does not include `response_mode` but the text a few paragraphs below this example appears to make omissions of `response_mode` illegal:

> The value of the response_mode parameter MUST be w3c_dc_api when the response is neither signed nor encrypted and w3c_dc_api.jwt when the response is signed and/or encrypted as defined in [Section 6.3](https://openid.net/specs/openid-4-verifiable-presentations-1_0-21.html#jarm).

I have a slight feeling that the intention was that `response_mode` could be omitted and would effectively default to `w3c_dc_api` for requests received via the API but I can't fully remember.

**Comment by bc-pi** [comment]
I'm about 99% sure that's just a mistaken omission in that example that was missed somewhere in the course of the 200 some comments and 40 some commits to #155.

**Comment by bc-pi** [comment]
#250 adds it to the example
