### ISSUE TITLE
VP Token format extensiblity

### ISSUE THREAD

**Issue by bc-pi** [openid/OpenID4VP#249]
looking at https://github.com/openid/OpenID4VCI/issues/386 "extensibility to Credential Response" and also thinking about some of the non breaking extensibility conversations reminded me that one of the anticipated things from introducing the new query language https://github.com/openid/OpenID4VP/pull/220 is "Define new format for the VP Token". For good reason as I recall and #178 shows some prospective examples.  But some work is needed on the VP Token now to allow for that down the road.

**Comment by bc-pi** [comment]
A reminder to @danielfett and/or a request that the Dr. tell me why I'm wrong.

**Comment by Sakurann** [comment]
what is the question/ask here..? defining a new structure of a VP Token in a new query language PR?

**Comment by jogu** [comment]
The new query language PR defines a new format for VP token.

The ask here is to make sure that VP 1.0 allows the format of VP token to be extended in  VP 1.1.
