### ISSUE TITLE
Permit the use of the new query language instead of presentation exchange.

### ISSUE THREAD

**Issue by martijnharing** [openid/OpenID4VP#255]
Section 5 and section 6 currently require the use of the presentation exchange specification in both the request and the response. To support implementations to use the new query language instead of the presentation exchange these requirements should be changed to optional.

Specifically:

Section 5 requires that `presentation_definition` or `presentation_definition_uri` MUST be present. This should be changed to MAY.
Section 6 requires that `presentation_submission` MUST be present. This should be changed to MAY.

**Comment by jogu** [comment]
Discussed on today's call, agreed to move to a PR.

**Comment by deshmukhrajvardhan** [comment]
Is someone working on it? if not I can volunteer.

**Comment by bc-pi** [comment]
> Is someone working on it? if not I can volunteer.

Correct me if I'm wrong but I believe @martijnharing volunteered to do it.

No?
