### ISSUE TITLE
Should Appendix A be referenced in section 7 as an option for Wallet Invocation?

### ISSUE THREAD

**Issue by samuelgoto** [openid/OpenID4VP#262]
[Section 7](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-wallet-invocation) goes over options that Verifiers have to invoke wallets. Since [Appendix A](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-openid4vp-profile-for-the-w) is one of those mechanisms, is there a reason it should not be noted there?

**Comment by bc-pi** [comment]
I suspect that was just an unintentional omission when the content of Appendix was added.  I think it should absolutely be listed as a one of those options.
