### ISSUE TITLE
Further clarify `redirect_uri` shape with `direct_post` responses

### ISSUE THREAD

**Issue by breynders-cb** [openid/OpenID4VP#272]
During a hackathon around UC5 Potential we came across interoperability issues due to a slight misinterpretation of [Section 6.2](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-6.2-22), particularly:

> The following new parameter is defined for use in the response from the endpoint: redirect_uri

combined with

> The following is a non-normative example of the response from the Verifier to the Wallet upon receiving the Authorization Response at the Response Endpoint (using a response_code parameter from [Section 11.5](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#implementation_considerations_direct_post)):
> 
> HTTP/1.1 200 OK
> Content-Type: application/json
> Cache-Control: no-store
> 
> {
>   "redirect_uri": "https://client.example.org/cb#response_code=091535f699ea575c7937fa5f0f454aee"
> }`

Other than the "non-normative example", it was never clearly stated that the `redirect_uri` will return in the response body as a JSON object and there were interpretations that used location headers instead. 

I think stating that the response body is supposed to be a JSON object with just 1 field (`redirect_uri`) is enough to make it 100% clear.

**Comment by jogu** [comment]
Good information, thanks! I've tried to resolve here: https://github.com/openid/OpenID4VP/pull/273
