### ISSUE TITLE
Make OID4VP's Query Language Format Agnostic

### ISSUE THREAD

**Issue by decentralgabe** [openid/OpenID4VP#284]
> I generally see risk in statically defining formats this query language works against. I would rather see us leverage a registry with associated guidance on how to plug into the general query language structure.

> similarly I would not support merging this PR without including at least w3c verifiable credentials - probably plain ID tokens/JWTs would be good too. the world is bigger than mdoc and ietf sd jwt vc

_Originally posted by @decentralgabe in https://github.com/openid/OpenID4VP/pull/266#discussion_r1809480899_

**Comment by paulbastian** [comment]
I agree here, I would rather see the format specific parameters to be defined in each Format of Appendix B

**Comment by awoie** [comment]
> I agree here, I would rather see the format specific parameters to be defined in each Format of Appendix B

I agree that this would be a cleaner approach. I believe I made a similar proposal earlier in the process. To be clear, I'd support having something like @pmhsfelix proposed [here](https://github.com/openid/OpenID4VP/pull/266#discussion_r1811011912) as well:

```
- vc+sd-jwt
  - path - REQUIRED (...)
- mso_mdoc
  - namespace: REQUIRED (...)
  - claim_name: REQUIRED (...)
```

**Comment by danielfett** [comment]
At the minimum, we should move the format-specific parts to the appendix (that would be only editorial).

**Comment by Sakurann** [comment]
resolve by https://github.com/openid/OpenID4VP/pull/340
