### ISSUE TITLE
Using HTTP Message Signatures (RFC 9421)?

### ISSUE THREAD

**Issue by cyberphone** [openid/OpenID4VP#291]
I may have read the specification poorly but it seems that OpenID4VP is not using HTTP Message Signatures (RFC 9421).

This is somewhat surprising since the FAPI WG have decided to replace their current signature scheme with RFC 9421.

FWIW, personally I'm not a fan of RFC 9421 since it doesn't support message serialization in a reasonable way, greatly limiting its usability in systems depending on embedding, countersigning, etc.  Requiring specific signature containers for HTTP is also a drawback.  The only obvious benefit is the absence of Base64Url-encoding.

**Comment by jogu** [comment]
We don't have any protected resource endpoints in OID4VP.

**Comment by cyberphone** [comment]
Thanx!  Sounds logical.
