### ISSUE TITLE
Payment UX Issues

### ISSUE THREAD

**Issue by cyberphone** [openid/OpenID4VP#313]
The following image is a commented extract from a recent document by the EU Digital Identity Wallet Consortium (EWC).  Compared to Apple Pay it appears to be rather awkward to use.  Since most of the UX issues are rooted in **OpenID4VP**, it might be a good idea creating a dedicated payments WG or at least a _Special Interest Group_: https://github.com/openid/OpenID4VP/issues/188.

![PayByBank](https://cyberphone.github.io/doc/payments/pay-by-bank-ewc-2024-10-21.png)

**Comment by cyberphone** [comment]
Well, the depicted system builds on a combination of OAuth/OIDC and OpenID4VP.  There are IMO a few problems with this:
- Through its superior UI and higher functionality, Apple Pay remain the "gold standard".  However, according to EUIDW proponents, the EU intend (through legal means), _forcing their solution on the market_.
- Banks in Europe have /forced by the PSD2 regulation), at sizeable costs already implemented support for SCA-based payment transactions, usually via their mobile banking apps.  According to the Open Banking Ltd. leadership, these solutions have gotten pretty good traction as well.

In addition, the fact that the DigitalLabor and the EWC solutions have almost nothing in common, _has recently caught the attention of the European Commission_.

There are other things worth mentioning, but they are probably more suited for the Ad-Hoc finance/payments Task Force the European Commission is about to launch.

Related link:
https://www.linkedin.com/posts/andersrundgren_the-open-banking-world-seem-to-disagree-on-activity-7260874268899483648--O80/

**Comment by cyberphone** [comment]
Continuing.  Since payments do neither map directly to the classical three-party OAuth2 schema, nor to the ARF, a credible payment activity should begin by identifying the actors and their respective roles.

The most striking difference compared to "credential presentation" is that Merchants are not relying parties; they only need a "proof of payment", which only the payment network can provide.

This notion also introduces privacy concerns.  The DigitalLabor solution does not take privacy in consideration.  Although the EWC solution (through a 3D Secure-like flow), honors privacy, it comes at the expense of a pretty awkward UI.

Apple Pay have none of these issues.

**Comment by Sakurann** [comment]
that explanation is still not actionable for a technical standard. should issuer metadata be changed in VCI? sd-jwt vc type metadata? etc.

**Comment by cyberphone** [comment]
As long we haven't defined what "we" want in terms of _functionality_, it seems futile trying to come up with actionable items related to technical standards.  _This is what I hope the EC Ad-Hoc Task Force will address_.

That the banks already have a working solution makes this an "existential" issue as well.  The lack of interest from Open Banking Ltd. and the Berlin Group indicates that dropping this part of the EUIDW project is a viable idea.

**Comment by jogu** [comment]
> As long we haven't defined what "we" want in terms of functionality, it seems futile trying to come up with actionable items related to technical standards. This is what I hope the EC Ad-Hoc Task Force will address.

So can we close this for now and wait to see what the task force comes back with? Without that information I (like Kristina) struggle to see what we can do. We need a concrete thing that people want to do with OID4VP and that they need changes to OID4VP to achieve.

**Comment by cyberphone** [comment]
Before closing this issue, it would of course be a bit useful to know _your_ preferences regarding high-level goals for the EUIDW payment solution.

**Comment by jogu** [comment]
I don't think expressing opinions on high level goals for the EUDIW payment solution is in the DCP WG's scope, though I think you're asking for my personal opinions - my personal opinion is that I don't have a good enough understanding of the law around EUDIW payments to be able to express an opinion on the actual technical solutions that are trying to implement that law.

**Comment by cyberphone** [comment]
Given that the two only known implementations are completely different, I do the conclusion that nobody knows how to interpret the EUIDW legal framework in a payment setting.  However, the "intent" must of course be adhered to.

If we take SCA as an example, Apple Pay surely meets the SCA requirement, although their way of accomplishing this goal is through a different method than used by Open Banking à la UK. 

Personally, I would be much more worried that a failed, underperforming, or market-wise redundant payment solution could cast a shadow over the entire project, including the Open ID foundation.  That the DigitalLabor request is _magnitudes_ more complex than Apple Pay indicates that we already are on a _dangerous path_.

**Comment by cyberphone** [comment]
OAuth2-based payment authorization schemes à la EWC, also seem to be constrained by the fact that Merchants represent an entity outside of the OAuth2 core.  It is at least unclear to me how gas station payments could be performed in a logical way: `RESERVE_MAX_AMOUNT`, later followed by a `CHARGE_ACTUAL_AMOUNT`.  If this observation is correct, we are clearly at an impasse.

**Comment by cyberphone** [comment]
The following image from the most recent specification by Open Banking Ltd., highlights this issue: Merchants aren't a part of the plot.  The EWC and DigitalLabor implementaters have thus been forced coming up with their own take on how to integrate Merchants in a scheme that (originally) wasn't designed for that:

![Open Banking Payment Authorization](https://openbankinguk.github.io/read-write-api-site3/assets/img/PaymentStatusModelTriangle.15d76462.png)

**Comment by Sakurann** [comment]
closing per https://github.com/openid/OpenID4VP/issues/196#issuecomment-2507161749
