### ISSUE TITLE
Editorial: Terminology section is not sorted

### ISSUE THREAD

**Issue by timcappalli** [openid/OpenID4VP#334]
I noticed that the Terminology section is not sorted. Should we sort alphabetically?

https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-terminology

**Comment by Sakurann** [comment]
Is that a rule or a convention? I see OIDC.Core does it, but few IETF specs I looked up did not seem to care..?

**Comment by timcappalli** [comment]
Nothing formal, but typically lists of words are alphabetized (when ordering is not important).
