### ISSUE TITLE
Enable DCQL requesting more than a single credential

### ISSUE THREAD

**Issue by peppelinux** [openid/OpenID4VP#345]
In [6.1. ](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#section-6.1)[Credential Query](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-credential-query)

we read

A Credential Query is an object representing a request for a presentation **of one Credential**.

Is there any practical reason to limit the presentation request to a single Credential?
Since the query language technically supports more than one Credential, it would be beneficial to remove this limit.

**Comment by c2bo** [comment]
DCQL allows to request more than one credential. A valid DCQL Query would look like this (I removed parts of the example of the spec for simplicity):

```json
{
  "credentials": [
    {
      "id": "pid",
      "format": "dc+sd-jwt",
      "meta": {
        "vct_values": ["https://credentials.example.com/identity_credential"]
      },
      "claims": [
        {"path": ["given_name"]},
        {"path": ["family_name"]},
        {"path": ["address", "street_address"]}
      ]
    },
    {
      "id": "other_pid",
      "format": "dc+sd-jwt",
      "meta": {
        "vct_values": ["https://othercredentials.example/pid"]
      },
      "claims": [
        {"path": ["given_name"]},
        {"path": ["family_name"]},
        {"path": ["address", "street_address"]}
      ]
    }
  ]
}
```
You are looking at the section that is describing the elements of `credentials` which are singular Credential Queries (values x,y,z from credential xyz), but `credentials` describes the overall request. See:
> credentials:
REQUIRED. A non-empty array of Credential Queries as defined in [Section 6.1](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#credential_query) that specify the requested Verifiable Credentials.
credential_sets:
OPTIONAL. A non-empty array of credential set queries as defined in [Section 6.2](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#credential_set_query) that specifies additional constraints on which of the requested Verifiable Credentials to return.

If `credentials` is present and `credential_sets` is not present, you are requesting all credentials in the `credentials` array as descrbied in https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#section-6.3.1.2.

**Comment by Sakurann** [comment]
I think the question has been answered?
