### ISSUE TITLE
Value used for 'aud' in SD-JWT key-binding JWT needs to be normatively defined

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#350]
There doesn't appear to be anywhere that the actual value to be used in 'aud' in an SD-JWT key binding JWT is defined.

[SD-JWT](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-14.html#section-4.3) only says:

> aud: REQUIRED. The intended receiver of the Key Binding JWT. How the value is represented is up to the protocol used and out of scope of this specification.

[SD-JWT VC](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-06.html#section-4.1) doesn't seem to say anything normative.

OID4VP doesn't seem to say anything normative.

HAIP doesn't currently say anything normative, but I'm also not sure HAIP is the right place to define this.

I suggest adding a clause in the SD-JWT credential format section in VP saying:

> `aud` in the Key Binding JWT MUST be the `client_id`.

**Comment by awoie** [comment]
> There doesn't appear to be anywhere that the actual value to be used in 'aud' in an SD-JWT key binding JWT is defined.
> 
> [SD-JWT](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-14.html#section-4.3) only says:
> 
> > aud: REQUIRED. The intended receiver of the Key Binding JWT. How the value is represented is up to the protocol used and out of scope of this specification.
> 
> [SD-JWT VC](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-06.html#section-4.1) doesn't seem to say anything normative.
> 
> OID4VP doesn't seem to say anything normative.
> 
> HAIP doesn't currently say anything normative, but I'm also not sure HAIP is the right place to define this.
> 
> I suggest adding a clause in the SD-JWT credential format section in VP saying:
> 
> > `aud` in the Key Binding JWT MUST be the `client_id`.

I agree that this is needed.
