### ISSUE TITLE
Does the `vp_token` necessarily need to be a VerifiablePresentation?

### ISSUE THREAD

**Issue by samuelgoto** [openid/OpenID4VP#56]
In section [6.1](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#section-6.1-2.2), IIUC, it seems that the resulting `vp_token` needs to be a `VerifiablePresentation`. 

Is that a general term for "verifiable presentations", or are we specifically talking about the one defined [here](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations) and [here](https://www.w3.org/2018/credentials/v1)?

And, if the latter, are we confident that these [VerifiablePresentations](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations) can properly encapsulate the presentation of ISO MDocs?

**Comment by c2bo** [comment]
Terminology introduces the terms as such:

> Verifiable Presentation (VP):
A Holder-signed Credential whose authenticity can be cryptographically verified to provide Cryptographic Holder Binding. Can be of any format used in the Issuer-Holder-Verifier Model, including, but not limited to those defined in [[VC_DATA](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#VC_DATA)], [[ISO.18013-5](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#ISO.18013-5)] (mdoc) and [[Hyperledger.Indy](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#Hyperledger.Indy)] (AnonCreds).

> W3C Verifiable Presentation:
A Verifiable Presentations compliant to the [[VC_DATA](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#VC_DATA)] specification.


But that is a good point - we should make sure people understand, that this can basically be whatever (and the protocol does not care). Do you think this should be formulated differently/clearer in section 6 to avoid confusion?

For the specific question regarding ISO Mdoc: https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#appendix-A.3.2-6 gives an example for `vp_token` in ISO mdl format

**Comment by Sakurann** [comment]
duplicative of #6

**Comment by samuelgoto** [comment]
> Has the question been answered? can this issue be closed?

I believe so, closing.
