### ISSUE TITLE
Unclear whether redirect_uri is allowed in Response Mode direct_post

### ISSUE THREAD

**Issue by cryptphil** [openid/OpenID4VP#58]
In Section [6.2](https://github.com/openid/OpenID4VP/blob/main/openid-4-verifiable-presentations-1_0.md?plain=1#L545) in the specification, it says that for Response Mode `direct_post`:

> response_uri: (...) When the response_uri parameter is present, the redirect_uri Authorization Request parameter MUST NOT be present. If the redirect_uri Authorization Request parameter is present when the Response Mode is direct_post, the Wallet MUST return an invalid_request Authorization Response error.

But the second [Note](https://github.com/openid/OpenID4VP/blob/main/openid-4-verifiable-presentations-1_0.md?plain=1#L549) indicates that when the Client Identifier scheme is `redirect_uri` with `direct_post`, the `redirect_uri` and the `response_uri` both have to be present (and `response_uri=client_id`). 
In my understanding, this conflicts with the specification above as `redirect_uri` must note be present when for Response Mode `direct_post` and `redirect_uri` must not be used in conjunction with `response_uri`.

**Comment by jogu** [comment]
I don't see the conflict - the second note reads:

> Note: If the Client Identifier scheme `redirect_uri` is used in conjunction with the Response Mode `direct_post`, and the `response_uri` parameter is present, the `client_id` value MUST be equal to the `response_uri` value.

This note is not not talking about the `redirect_uri` parameter, it is talking about the redirect_uri client id scheme. (The redirect_uri client id scheme is weird when used with direct_post, as it requires that the client_id matches the response_uri.)

**Comment by cryptphil** [comment]
@jogu Ah I see where the confusion came from, I was reading the spec [https://openid.net/specs/openid-4-verifiable-presentations-1_0.html](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html) from 21 April 2023 where the sentence still is:

> If the Client Identifier scheme redirect_uri is used in conjunction with the Response Mode direct_post, and the **redirect_uri** parameter is present, the client_id value MUST be equal to the response_uri value.

In the current WG draft, this mistake is already fixed; thank you!
