### ISSUE TITLE
Explanation of presentation_submission should be independent of credential format

### ISSUE THREAD

**Issue by tlodderstedt** [openid/OpenID4VP#63]
The current description in section 6.1. is tight to W3C VCs.

Here is one example

> The path_nested object inside an Input Descriptor Mapping Object is used to describe how to find a returned Credential within a Verifiable Presentation, and the value of the path field in it will ultimately depend on the credential format. 

The text needs to be modified to be format agnostic. Additionally, we might want to move format specific text into the W3C VC profile.

**Comment by nemqe** [comment]
Given that presentation_submission structure is / or should be moving away from the spec, this line shpould maybe be removed or amended

> A descriptor_map element MUST contain a path_nested parameter referring to the actual Credential carried in the respective Verifiable Presentation.

located here: https://github.com/openid/OpenID4VP/blob/9a8ac76f93d0240767d92152085ae08c420d71cc/openid-4-verifiable-presentations-1_0.md?plain=1#L603
