### ISSUE TITLE
Can you submit multiple vp tokens for a single presentation definition?

### ISSUE THREAD

**Issue by TimoGlastra** [openid/OpenID4VP#69]
I want to cross-reference an issue I opened in the PEX specification around creating multiple VPs and single presentation submission for a single presentation definition.

The issue contains more context, but the question boils down to: Can you submit multiple VP tokens for a single presentation definition?

This seems related to this specification, and is something that came up during the recent JFF Plugfest. We ended up supporting it on our wallet side, as well as MATTR has added support for submitting multiple VP tokens for a single presentation definition.

This is the issue in the PEX specification: https://github.com/decentralized-identity/presentation-exchange/issues/462

And this it the issue that started the discussion in Sphereon's SIOP/OpenID4VP implementation: https://github.com/Sphereon-Opensource/SIOP-OID4VP/issues/62

**Comment by Sakurann** [comment]
> the question boils down to: Can you submit multiple VP tokens for a single presentation definition?

you can present multiple VPs (inside one VP Token - assume it is a typo in the question and you meant VP, not VP token) for a single presentation_definition. if verifier is requesting multiple VCs that are bound to a different holder key and both require cryptographic holder binding, the wallet does not have a choice but to return multiple VPs. does oid4vp say anywhere that multiple VPs per presentation_definition is not allowed?

**Comment by TimoGlastra** [comment]
It came from a discussion i had with Niels in https://github.com/Sphereon-Opensource/SIOP-OID4VP/issues/62

But my question has since been answered in https://github.com/decentralized-identity/presentation-exchange/issues/462 and i forgot the close this issue.

Thanks for the extra confirmation that it is indeed possible!

**Comment by awoie** [comment]
@jogu @Sakurann we can probably close this one now.
