### ISSUE TITLE
Administrative Trust in the RP

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VP#7]
### Original Reporter: dwc8

Wallets may need to decide if RPs are administratively trusted prior to asking the user for consent to send credentials to the RP. \(Note administrative trust is not the same as cryptographic trust, which can be established with a TLS link to the RP.\) We have already specified a mechanism for RPs and wallets to administratively trust issuers, **regardless of the trust infrastructure used,** and we need a similar mechanism to enable trust in RPs. The following methods are suggested:

1. The RP adds a trust\_federation property to its metadata, listing the names of the trust federations that it purports to be a member of;
2. The RP sends its trust\_federation property values to the wallet along with the presentation request.

Note that the trust federation property values asserted by the RP may be true or false. It is the responsibility of the wallet to determine whether any of the values are true or not by using the method specified by its trust infrastructure. The inputs to this algorithm are: the name of the RP and the name of asserted trust federation.

‌

**Comment by awoie** [comment]
@jogu I believe this can close now, right? We merged client ID schemes and entity_id into the spec.

**Comment by jogu** [comment]
yeah, the issue Kristina mentioned ( https://bitbucket.org/openid/connect/issues/1798 ) is resolved so I think we can close this.
