### ISSUE TITLE
clarify this is an editor's draft in the title

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VP#70]
See https://github.com/openid/OpenID4VCI/pull/126

**Comment by awoie** [comment]
@paulbastian Note that this was reverted here https://github.com/openid/OpenID4VCI/commit/395414237c998c21cce9c533019014fc07933f48

**Comment by jogu** [comment]
This was temporary to get the version for the ID vote published - there's also a PR to put it back again: https://github.com/openid/OpenID4VCI/pull/260

**Comment by paulbastian** [comment]
Add the suggestion was accepted for openid4vci, shall I make a PR for this spec?

**Comment by awoie** [comment]
> Add the suggestion was accepted for openid4vci, shall I make a PR for this spec?

Created PR here #102
