### ISSUE TITLE
Clarification of optional response parameters

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VP#71]
Section 6.1 on response parameters state:
> Other parameters, such as state or code (from [[RFC6749](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#RFC6749)]), or id_token (from [[OpenID.Core](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#OpenID.Core)]), and iss (from [[RFC9207](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#RFC9207)]) MAY be included in the response as defined in the respective specifications.

However, RFC6749 says:
> state
         REQUIRED if the "state" parameter was present in the client
         authorization request.  The exact value received from the
         client.

The MAY in OpenID4VP is confusing here, either do not capitalize it or explicitly say that response parameters can be mandate by other specs.

**Comment by Sakurann** [comment]
rfc6749 says that stat must be present in the response only when it was present in the request, so may in section 6.1 is not a mistake.

**Comment by Sakurann** [comment]
@paulbastian has the question been answered?

**Comment by paulbastian** [comment]
I think the wording is still confusing, "may" would fit better, or "can". Capitalised MAY seem to contradict the MUST in RafC6749

**Comment by Sakurann** [comment]
alright. changed to `can` please review the PR.
