### ISSUE TITLE
Add SD-JWT VC Profile

### ISSUE THREAD

**Issue by tlodderstedt** [openid/OpenID4VP#74]
we need to add the presentation part of the SD-JWT VC profile to OID4VP (https://openid.github.io/oid4vc-haip-sd-jwt-vc/draft-oid4vc-haip-sd-jwt-vc.html#name-presentation-definition) before we can remove the profile from HAIP

**Comment by javereec** [comment]
I can contribute this section as I also believe it can be really useful.

Is there an expectation to use the exact same wording as in https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0-00.html?

**Comment by Sakurann** [comment]
@javereec would be great if you could do the PR! Yes, the starting point should be what we have in HAIP. the PR we did to move sd-jwt vc profile to the VCI might be helpful too: https://github.com/openid/OpenID4VCI/pull/128
