### ISSUE TITLE
Need better error description and examples for more common cases 

### ISSUE THREAD

**Issue by awoie** [openid/OpenID4VP#89]
The current specification does not provide error codes and examples of cases where the wallet does not have the credentials to answer a request, or when the user does not give consent to share the credentials with the RP.

We need to provide examples. 

While OID4VP allows to provide an error in that case, we should probably discuss whether it makes sense to introduce additional error codes for these more common cases:
- user did not provide consent or rejected the request.
- user does not have all the credentials in their wallet to answer the request.

Thoughts?

**Comment by awoie** [comment]
To be backward compatible, it is probably better to cover both cases with `access_denied`.

**Comment by Sakurann** [comment]
I think `access_denied` should be used when the `user did not provide consent or rejected the request`.
when the user `did not have all the credentials in their wallet to answer the request`, it is probably a good idea to define an error code dedicated to that, though I am not sure if there are any privacy implications of telling the user which credential is in the wallet or not.

**Comment by awoie** [comment]
> I think `access_denied` should be used when the `user did not provide consent or rejected the request`. when the user `did not have all the credentials in their wallet to answer the request`, it is probably a good idea to define an error code dedicated to that, though I am not sure if there are any privacy implications of telling the user which credential is in the wallet or not.

Yep, I think it is a privacy concern to return that error. That is why it would be better to hide this behind this more generic error code.
