### ISSUE TITLE
redirect_uri client_id_scheme: is response_uri optional?

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#93]
When using `client_id_scheme=redirect_uri`, you can omit redirect uri as per https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#client_metadata_management :

> the Verifier MAY omit the redirect_uri Authorization Request parameter

It would be logical to assume that when using `direct_post`  + `client_id_scheme=redirect_uri` you can also omit `response_uri`, however I think the current text is not clear. We should probably be explicit.

**Comment by awoie** [comment]
The only text we have that would cover this is:
> The response_uri value MUST be a value that the client would be permitted to use as redirect_uri when following the rules defined in [Section 5.7](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#client_metadata_management).

I agree that this is not very clear but according to the text above I'd assume it can be omitted.

**Comment by Sakurann** [comment]
we should add a general sentence that when direct_post is used, all restrictions other response modes have on `redirect_uri`, apply on `response_uri` request parameter. Sounds better than patching each instance.

**Comment by javereec** [comment]
I think the following also relates to this clause which I find confusing (Section 5.7)

> redirect_uri: This value indicates that the Verifier's redirect URI is also the value of the Client Identifier. In this case, the Authorization Request MUST NOT be signed, the Verifier MAY omit the redirect_uri Authorization Request parameter, and all Verifier metadata parameters MUST be passed using the client_metadata or client_metadata_uri parameter defined in [Section 5](https://openid.net/specs/openid-4-verifiable-presentations-1_0-ID2.html#vp_token_request).

In case of Response Mode `direct_post` the Client Identifier should be equal to `response_uri`

My first idea would be to change the wording slightly to clarify

> redirect_uri: This value indicates that the Verifier's redirect URI or response URI is also the value of the Client Identifier. In this case, the Authorization Request MUST NOT be signed, the Verifier MAY omit the redirect_uri Authorization Request parameter, and all Verifier metadata parameters MUST be passed using the client_metadata or client_metadata_uri parameter defined in [Section 5](https://openid.net/specs/openid-4-verifiable-presentations-1_0-ID2.html#vp_token_request).

**Comment by Sakurann** [comment]
@javereec yes, I think the text you point out is one of the places that need to be changed

**Comment by Sakurann** [comment]
> It would be logical to assume that when using direct_post + client_id_scheme=redirect_uri you can also omit response_uri, however I think the current text is not clear. We should probably be explicit.

@jogu I re-read the text and I think it is clear that the sentence you point out applies to any response mode. i mean, response mode is orthogonal to client_id_schemes. I think we can keep the text as-is?
