### ISSUE TITLE
Discrepancy between Response section & combining with SIOPv2 section

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VP#94]
Section 6 only defines 3 response_types that return VP tokens:

<img width="635" alt="Screenshot 2024-02-10 at 20 30 35" src="https://github.com/openid/OpenID4VP/assets/316456/c399e111-f9bd-41eb-a9e8-66966247d0b6">

whereas 'A.4. Combining this specification with SIOPv2' says that `response_type=id_token` can also return a VP token:

<img width="636" alt="Screenshot 2024-02-10 at 20 29 45" src="https://github.com/openid/OpenID4VP/assets/316456/247f6353-2653-494f-998d-08ccda5e1ce3">

It seems like either `id_token` should be added to the table in section 6, or A.4 should use `response_type=vp_token id_token`.

**Comment by Sakurann** [comment]
A.4 should use `response_type=vp_token id_token`.
