### ISSUE TITLE
Clarification needed on SIOP and client_metadata paragraph

### ISSUE THREAD

**Issue by awoie** [openid/OpenID4VP#96]
The current text has the following section:
> Usage of client_metadata or client_metadata_uri parameters with client_id that the Wallet might be seeing for the first time is mutually exclusive with the registration mechanism where Self-Issued OP assigns client_id to the Verifier after receiving Verifier metadata.

Can somebody remind me of the purpose of this paragraph?

**Comment by Sakurann** [comment]
I think it makes sense if you replace Self-Issued OP with the Wallet.

**Comment by Sakurann** [comment]
the purpose was to say that when verifier pre-registers with the wallet, it cannot use client_metadata parameters in the request.

**Comment by awoie** [comment]
> Usage of client_metadata or client_metadata_uri parameters with client_id that the Wallet might be seeing for the first time is mutually exclu

I tried to parse this paragraph again by replacing SIOP with wallet and I am still having some issues understanding what it means or why it is there in terms of actions wallets/verifiers have to perform.

Does it actually mean that client_metadata_uri and client_metadata must not be present if the wallet registered the verifier via other means?

**Comment by jogu** [comment]
@Sakurann I'm struggling with this part:

> assigns client_id to the Verifier after receiving Verifier metadata

Is this an operation internal to the wallet, or is there a mechanism where the wallet tells the verifier what client_id it must use in subsequence requests? Is this only applicable to some client_id_schemes because most seem to make client_id mandatory?

**Comment by Sakurann** [comment]
> Is this an operation internal to the wallet, or is there a mechanism where the wallet tells the verifier what client_id it must use in subsequence requests? Is this only applicable to some client_id_schemes because most seem to make client_id mandatory is the request?

assumes a possibility that there is a possibility for a wallet to tell the verifier which client_id to use. so it is basic oauth and is orthogonal to new client id schemes

**Comment by awoie** [comment]
@Sakurann Can you please give an example?

**Comment by Sakurann** [comment]
all the text is trying to say is "do not use client-metadata/client_metadata_uri if you have pre-registered clients".

**Comment by awoie** [comment]
> all the text is trying to say is "do not use client-metadata/client_metadata_uri if you have pre-registered clients".

Then, this text should be moved to the `pre-registered` in https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-5.7.

On a separate note, we should discuss in separate issue if this should be actually allowed for cases where the verifier wants to communicate ephemeral encryption keys.
