### ISSUE TITLE
Remove tautology from section 6

### ISSUE THREAD

**Issue by awoie** [openid/OpenID4VP#98]
Section 6 contains the following paragraph:
> A VP Token is only returned if the corresponding Authorization Request contained a presentation_definition parameter, a presentation_definition_uri parameter, or a scope parameter representing a Presentation Definition [Section 5](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#vp_token_request).

This is redundant since if this is not the case, an error is returned anyways.

**Comment by awoie** [comment]
In the context of OID4VP, there should be an error since it is required that either of those options are present.

**Comment by awoie** [comment]
> In the context of OID4VP, there should be an error since it is required that either of those options are present.

It is an OID4VP request if vp_token response type is present.

**Comment by jogu** [comment]
> It is an OID4VP request if vp_token response type is present.

That's not currently the case, https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#section-6 says that response_type=code can result in a vp_token.

**Comment by awoie** [comment]
Is the following statement accurate:
- a `vp_token` is returned if `response_type` includes `vp_token`.
- a `vp_token` is returned if `response_type` is `code` and either a recognized scope value, `presentation_definition`, or `presentation_definition_uri` parameter is present.

**Comment by jogu** [comment]
> a vp_token is returned if response_type includes vp_token.

This is not quite true, as you need to also pass a recognized scope value, presentation_definition, or presentation_definition_uri parameter as well.

**Comment by awoie** [comment]
> > a vp_token is returned if response_type includes vp_token.
> 
> This is not quite true, as you need to also pass a recognized scope value, presentation_definition, or presentation_definition_uri parameter as well.

My point was that if response_type is vp_token and none of the three options are included, you would receive an invalid_request error. Would you agree?

**Comment by jogu** [comment]
Ah, got it - yes, that's true.
